---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: "Create Github release"

inputs:
  VERSION:
    description: "Version to release on Github"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: "Create Github release"
      shell: bash
      run: |
        if gh release create "${{ inputs.VERSION }}" --generate-notes; then
          echo "Release ${{ inputs.VERSION }} created ✅" >> "$GITHUB_STEP_SUMMARY"
          echo "Release ${{ inputs.VERSION }} created ✅"
        else
          echo "Failed to create release ${{ inputs.VERSION }} ❌" >> "$GITHUB_STEP_SUMMARY"
          echo "Failed to create release ${{ inputs.VERSION }} ❌"
        fi
