# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Canonical Ltd.
name: Docker Build

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Name of the branch to checkout"
        required: false
        type: string
        default: ${{ github.ref }}
      build_directory:
        description: "Directory where to run the build command from"
        required: false
        type: string
        default: '.'
      make_target:
        description: "Makefile target to build"
        required: false
        type: string
        default: "docker-build"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: Build Docker image
        run: |
          cd ${{ inputs.build_directory }}
          make ${{ inputs.make_target }}
