# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Canonical Ltd.
name: Fossa Scan

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Name of the branch to checkout"
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: FOSSA scan
        uses: fossa-contrib/fossa-action@v3
        with:
          fossa-api-key: 6d304c09a3ec097ba4517724e4a4d17d
