# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Canonical Ltd.
name: Lint Helm Charts

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Find all Charts and Lint them
        run: |
          for dir in $(find . -maxdepth 1 -mindepth 1 -type d); do
            if [[ -f "$dir/Chart.yaml" ]]; then
              helm lint "$dir"
            fi
          done
