# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  license-check:
    uses: ./.github/workflows/license-check.yml
    with:
      branch_name: ${{ github.ref }}

  fossa-scan:
    uses: ./.github/workflows/fossa-scan.yml
    with:
      branch_name: ${{ github.ref }}
